const ResponseMessages = {
  SAVE: "Created Successfully",
  UPDATE: "Updated Successfully",
  NOT_FOUND: "Not Found",
  LOGIN_SUCCESS: "Logged In Successfully",
  LOGIN_FAILED: "Logged In Failed",
  UPDATE_FAILURE: "Failed To Update",
  DATA_RETRIEVED_SUCCESSFULLY: "Data Retrieved Successfully",
  INSUFFICIENT_DATA: "Insufficient Data On Request",
  PROFILE_NOT_APPROVED: "Your profile is not approved",
  PASSWORD_NOT_MATCH: "password is not matching",
  SAVE_FAIL: "Failed to create",
  ORDER_ALREADY_CONFIRMED: "Session has expired",
  UNAUTHORIZED: "Unauthorized Access",
  VALIDATION_ERROR: "Validation errors",
  API_NOT_FOUND: "API End Point Not Found",
  INTERNAL_SERVER_ERROR: "Internal Server Error",
  VALIDATION_ERROR: "Validation error occurred",
  UNIQUE_CONSTRAINT_ERROR: "Unique constraint error occurred",
  FOREIGN_KEY_CONSTRAINT_ERROR: "Foreign key constraint error occurred",
  DATABASE_ERROR: "Database error occurred",
  INTERNAL_SERVER_ERROR: "Internal server error occurred",
  DATA_RETRIEVED_SUCCESSFULLY: "Data retrieved successfully",
  USER_REGISTERED_SUCCESSFULLY:"Sucessfully Registered",
  User_Exist:"User Already Exist ,please login",
  OTP_SENT:"Otp Sent To Mobile Number",
  INVALID_OTP:"You Entered An Wrong OTP",
  CUSTOMER_NOT_EXIST:"customer is not exist"
};

module.exports = ResponseMessages;
